import { MainLayout } from "@/components/layouts";
import StoreProvider from "@/components/layouts/store-provider/StoreProvider";
import { useGetMemesQuery } from "@/store/services/memesApi";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <MainLayout />

          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
